import Cocoa

enum ClipPayload {
    case text(String)
    case image(Data)
}

final class ClipboardWatcher {
    private var lastChangeCount: Int
    private var timer: Timer?

    var onNewClip: ((ClipPayload) -> Void)?

    init() {
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.check()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if let types = pb.types {
            let skipTypes: Set<String> = [
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
                "com.copaste.internal",
            ]
            for t in types where skipTypes.contains(t.rawValue) {
                return
            }
        }

        // Prefer text when both are present (e.g. apps that put a label
        // alongside a screenshot), so plain copy-paste of text never gets
        // hijacked by image data.
        if let str = pb.string(forType: .string), !str.isEmpty {
            onNewClip?(.text(str))
            return
        }

        if let data = imageData(from: pb) {
            onNewClip?(.image(data))
        }
    }

    private func imageData(from pb: NSPasteboard) -> Data? {
        // Try PNG first (smaller), fall back to TIFF — Database normalizes both to PNG.
        if let png = pb.data(forType: .png) { return png }
        if let tiff = pb.data(forType: .tiff) { return tiff }
        return nil
    }
}
