import Cocoa

final class ClipboardWatcher {
    private var lastChangeCount: Int
    private var timer: Timer?

    var onNewClip: ((String) -> Void)?

    init() {
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.check()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    private func check() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if let types = pb.types {
            let skipTypes: Set<String> = [
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
                "com.copaste.internal",
            ]
            for t in types where skipTypes.contains(t.rawValue) {
                return
            }
        }

        guard let str = pb.string(forType: .string), !str.isEmpty else { return }
        onNewClip?(str)
    }
}
